services:
  helpsite:
    build: .
    container_name: kon_demo_sites
    ports:
      - "5020:5020"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL:-}
      - DEVREV_PLUG_APP_ID=${DEVREV_PLUG_APP_ID:-}
      - DEVREV_PLUG_ENABLE_SESSION_RECORDING=${DEVREV_PLUG_ENABLE_SESSION_RECORDING:-false}
      - DEVREV_PLUG_PROMPT_USER_IP=${DEVREV_PLUG_PROMPT_USER_IP:-true}
      - DEVREV_APPLICATION_ACCESS_TOKEN=${DEVREV_APPLICATION_ACCESS_TOKEN:-}
      - DEVREV_PAT=${DEVREV_PAT:-}
      - DEVREV_CONVERSATION_UPDATE_SEND_SCHEMA_SPEC=${DEVREV_CONVERSATION_UPDATE_SEND_SCHEMA_SPEC:-true}
      - DEVREV_CONVERSATION_UPDATE_TENANT_FRAGMENT=${DEVREV_CONVERSATION_UPDATE_TENANT_FRAGMENT:-true}
      - DEVREV_CONVERSATION_UPDATE_VALIDATE_REQUIRED_FIELDS=${DEVREV_CONVERSATION_UPDATE_VALIDATE_REQUIRED_FIELDS:-false}
      - DEVREV_CONVERSATION_CUSTOM_FIELD_USER_IP=${DEVREV_CONVERSATION_CUSTOM_FIELD_USER_IP:-tnt__user_ip}
      - DEVREV_ACCOUNT_REF=${DEVREV_ACCOUNT_REF:-}
      - DEVREV_WORKSPACE_REF=${DEVREV_WORKSPACE_REF:-}
    restart: unless-stopped
